config/routes.rb
Rails.application.routes.draw do
  resources :ordered_items
  root 'static_public#landing_page'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :categories do
    resources :products
  end

  resources :order
  resources :cart
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :order, optional: true

    validates :total_price, numericality: { greater_than: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :title, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :cart , optional: true
    belongs_to :product

    validates :quantity, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :ordered_items

    validates :total_price, presence: true
    validates :total_price, numericality: { greater_than: 0 }
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
    belongs_to :order
    belongs_to :product
    belongs_to :user

    validates :quantity, numericality: { greater_than: 0}
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :cart, optional: true
    belongs_to :category, optional: true
    has_many :items, dependent: :destroy

    validates :name, presence: true
    validates :price, presence: true
    validates :price, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ordered_items, through: :cart
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
        user = User.create(name: data['name'],
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def create
        cart = Cart.find_or_create_by(user: current_user)
        product = Product.find(params[:product_id])
        item = Item.find_or_create_by(product: product, cart: cart)
        item.quantity ? item.update(quantity: (item.quantity + params[:quantiy].to_i)) : item.update(quantity: params[:quantiy])
        update_total_price()
        redirect_to cart_path(cart.id)
    end

    def show
        @cart = Cart.find_or_create_by(user: current_user)
        @items = Item.where(cart: @cart)
        render 'carts/show'
    end

    def update
        cart = Cart.find_or_create_by(user: current_user)
        product = Product.find(params[:product_id])
        item = Item.find_or_create_by(product: product, cart: cart)
        
        if item_params[:quantity].to_i < 1
            item.destroy
            update_total_price()
        else
            item.update(item_params)
            update_total_price()
        end

        redirect_to cart_path(cart.id)
    end

    private

    def item_params
        params.require(:item).permit(:quantity)
    end

    def update_total_price
        cart = Cart.find_or_create_by(user: current_user)
        items = Item.where(cart: cart)
        total = 0
        
        items.each do |i|
            total += (i.product.price.to_i * i.quantity.to_i)
        end

        cart.update(total_price: total.to_i)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        
    end

    def create # current_user ? current_user.name : 'Rails Store'
        cart = Cart.find_or_create_by(user: current_user)
        product = Product.find(params[:product_id])
        item = Item.find_or_create_by(product: product, cart: cart)
        item.quanity ? item.update(quanity: (item.quanity + params[:quantiy].to_i)) : item.update(quanity: params[:quantiy])
        update_total_price()
        redirect_to cart_path(cart.id)
    end

    def show
        @cart = Cart.find_or_create_by(user: current_user)
        @items = Item.where(cart: @cart)
        render 'carts/show'
    end

    def update
        cart = Cart.find_or_create_by(user: current_user)
        product = Product.find(params[:product_id])
        item = Item.find_or_create_by(product: product, cart: cart)
        
        if item_params[:quanity].to_i < 1
            item.destroy
            update_total_price()
        else
            item.update(item_params)
            update_total_price()
        end

        redirect_to cart_path(cart.id)
    end

    private

    def item_params
        params.require(:item).permit(:quanity)
    end

    def update_total_price
        cart = Cart.find_or_create_by(user: current_user)
        items = Item.where(cart: cart)
        total = 0
        
        items.each do |i|
            total += (i.product.price.to_i * i.quanity.to_i)
        end

        cart.update(total_price: total.to_i)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    def new
        cart = Cart.find_or_create_by(user: current_user)
        @items = Item.where(cart: cart)

        @order_total = 0
        @items. each do |i|
            @order_total = @order_total + (i.product.price * i.quantity)
        end

        @order = Order.create!(user: current_user, total_price: @order_total, status: 'Pending')
        @items. each do |i|
            OrderedItem.create!(quantity: i.quantity, product: i.product, order: @order, user: current_user)
            i.destroy
        end

        cart.destroy

        render 'orders/new'
    end

    def show
        @ordered_items = OrderedItem.where(user: current_user)

        render 'orders/show'
    end
end

app/controllers/ordered_items_controller.rb
class OrderedItemsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
        cart = Cart.find_or_create_by(user: current_user)
        @items = Item.where(cart: cart)
        render 'orders/new'
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @category = Category.find(params[:category_id])
        @products = @category.products.order(:price)
    end
end

app/controllers/static_public_controller.rb
class StaticPublicController < ApplicationController
    skip_before_action :authenticate_user!, only: %i[landing_page privacy]
    def landing_page
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<div>
    <div class="categories">
        <h1 class="cart">Your Cart</h1>
        <% if @items.length > 0 %>
            <% @items.each do |i| %>
                <%= form_for i, url: cart_path do |f| %>
                    <a id="category" class="list-group-item list-group-item-action"> <h4 id="product"> <%= i.product.name %> </h4>
                        <br>
                        <%= hidden_field_tag :product_id, i.product.id %>
                        <%= f.label "Quantity:"%>
                        <%= f.number_field :quantity, min: 0, max: 10 %>
                        <%= f.label "Price (#{i.quantity}) : $ " %>
                        <%= f.label (i.product.price.to_i * i.quantity.to_i) %>
                        <%= f.submit "Update Cart" %>
                    </a>
                <% end %>
            <% end %>
            <h5> Total Price: $<%= @cart.total_price %> </h5>
            <h6 class="backwards"> <%= link_to "Check Out", new_order_path%> </h6>
            <h6 class="backwards"> <%= link_to "Back to Categories", categories_path%> </h6>
        <% else %>
            <a id="category" class="list-group-item list-group-item-action"> <h3 class="empty"> Your Cart is Empty! </h3> </a>
            <h6 class="backwards"> <%= link_to "Back to Shop", categories_path%> </h6>
        <% end %>
    </div>
</div>

app/views/orders/new.html.erb
<div>
    <div class="categories">
        <h1>Order Placed!</h1>
        <% @items. each do |i| %>
            <a id="category" class="list-group-item list-group-item-action">
                <h4 id="product">
                    <%= "(#{i.quantity})  " %>
                    <%= "#{i.product.name} : " %>
                    <%= "$#{i.product.price}" %>
                </h4>
            </a>
        <% end %>
        <a id="category" class="list-group-item list-group-item-action">
            <h2>Order Total: <%= "$#{@order_total}" %></h2>
        </a>
        <h6 class="backwards"> <%= link_to "View All Orders", order_path(current_user.id)%> </h6>
        <h6 class="backwards"> <%= link_to "Back to Cart", cart_path(current_user.id)%> </h6>
    </div>
</div>

app/views/orders/show.html.erb
<div>
    <div class="categories">
        <h1>Your Orders</h1>
            <% if @ordered_items.length > 0%>
                <% @ordered_items. each do |i| %>
                    <a id="category" class="list-group-item list-group-item-action">
                        <h4 id="product"> 
                            <%= i.product.name %>
                            <%= "(x#{i.quantity})" %>
                            <%= "$#{i.product.price}" %>
                        </h4>
                        <h4><%= "Ordered @ #{i.created_at}" %></h4>
                    </a>
                <% end %>
            <% else %>
                <a id="category" class="list-group-item list-group-item-action">
                    <h4>You Have Not Ordered Anything</h4>
                </a>
            <% end %>
            <h6 class="backwards"> <%= link_to "Continue Shopping", categories_path%> </h6>
            <h6 class="backwards"> <%= link_to "Back to Home", root_path%> </h6>
    </div>
</div>